### ISSUE TITLE
Create data for tables.

### ISSUE THREAD

**Issue by anony391** [anony391/data391#2]
Please create data that can be tested and real. :)

**Comment by cchan5** [comment]
Added eight people for users, persons, and family_doctor tables. We can add the rest later as we go along I guess...I have no idea what to do for the radiology records table.

**Comment by rjynn** [comment]
Fixed the sql statements :) now works. and the data has been added to the tables on server. pls check for reference for testing because i've changed some of the data. original data did not have doctors as person which is against foreign contraints :)
